export const SET_VISA = 'SET_VISA'
export const SET_USER = 'SET_USER'
export const SET_ADDRESS='SET_ADDRESS'
export const SET_SET_ADDRESS_LIST='SET_SET_ADDRESS_LIST'
export const SET_NEEDINFO='SET_NEEDINFO'
export const SET_COUPON = 'SET_COUPON'